### ISSUE TITLE
[Suggestion] "Help_Proximity_Voice_Chat" Text (Deutsch.lua)

### ISSUE THREAD

**Issue by Mawarii** [Niklaskerl200l/Buben-Voice-Chat#1]
Hey,
I'll write this issue in German, because it is about the German language file.

Das soll nur ein kleiner Vorschlag sein, weils mir aufgefallen ist. Ich persönlich finde es immer bisschen ungewohnt, wenn man in Spielen gesiezt wird. Deshab hätte ich einen Vorschlag für den Text von Help_Proximity_Voice_Chat.
Anstelle von `"Mit den Schiebereglern können Sie die Reichweite des globalen Voice-Chats anpassen"` könnte man etwas schreiben wie `"Mit den Schiebereglern kann die Reichweite des globalen Voice-Chats angepasst werden"`.
Damit muss nicht gesiezt oder geduzt werden und der Inhalt bleibt gleich.

Ist auf jeden Fall ein richtig cooles Addon. Danke fürs Bereitstellen :)

**Comment by Niklaskerl200l** [comment]
Hi,

ja das hast du Recht ist ein guter Punkt passe ich nachher gleich an.

**Comment by Niklaskerl200l** [comment]
Habe ich angepasst und auf Steam veröffentlicht.
