### ISSUE TITLE
Erhöhen der maximalen Reichweite

### ISSUE THREAD

**Issue by Benni0706** [Niklaskerl200l/Buben-Voice-Chat#3]
Hi, wäre es möglich, den Maximalwert für das Reichweiten-Convar zu erhöhen?

**Comment by Niklaskerl200l** [comment]
Klar ist möglich hast du einen Speziellen Wunsch was das Maximum sein soll?

**Comment by Benni0706** [comment]
Vielen Dank für die schnelle Antwort. Wir verwenden das Addon praktisch nur für den Toggle Key als globalen Sprachchat, da [TTT2/Sandbox] Voice Chat Toggle Key leider einen nervigen Bug hat, der dazu führt, dass man zu Beginn jeder Runde gemuted wird, ohne dass es angezeigt wird. Daher bräuchten wir eigentlich gar keine Begrenzung, so etwas wie 20000 sollte aber auch alle mal ausreichen.

**Comment by Niklaskerl200l** [comment]
Ah ok verstehe. Heißt das mit der Reichweite verwendet ihr also quasi gar nicht. Weil dann würde ich eine Einstellung für Reichweite unbegrenzt hinzufügen.

**Comment by Benni0706** [comment]
Genau, das wäre sogar noch besser. Danke!

**Comment by Niklaskerl200l** [comment]
Ok, habe es hinzugefügt und auf Steam veröffentlicht. Hast jetzt eine Option im F1 Menü zum Deaktivieren der Voice Chat Reichweite.

Allerdings ist mir beim Testen aufgefallen, dass trotz unbegrenzter Reichweite, wenn man 3D Voice an hat es immer leiser wird, bis man jemand gar nicht mehr hört. Sieht mir nach einem normalen Verhalten von TTT oder evtl. auch von TTT2 aus. Solltest du aber 3D Voice aus haben funktioniert es.

![grafik](https://github.com/Niklaskerl200l/Buben-Voice-Chat/assets/75811870/6e118140-81f4-4181-ac74-ccc142072a07)

**Comment by Benni0706** [comment]
Jo, wir verwenden eh kein 3d Voice. Danke auf jeden Fall nochmal für das schnelle Umsetzen!

**Comment by Niklaskerl200l** [comment]
Ah ok, um so besser, dann funktioniert es.
